/* ============================================================
   TUS PRODUCTOS
   ============================================================
   Generado automaticamente desde las fotos de  img/ultimas.
   El nombre de cada producto es el nombre del archivo de la foto.

   Para agregar un producto: copia un bloque { ... } y pegalo abajo.
   Para sacar uno del catalogo: borra su bloque.
   Los precios NO van aca (ver precios-internos.txt).
   ============================================================ */

const CONFIG = {
  nombreNegocio: "Rincón de Dulce de Leche",

  // PONE TU NUMERO DE WHATSAPP (con codigo de pais, sin + ni espacios)
  whatsapp: "5492616711790",

  ubicacion: "Mendoza, Argentina",

  // Segundo telefono, el que se muestra en Contacto (vacio = no se muestra)
  telefono2: "5492612144655",
  moneda: "$",
  mensajePedido: "Hola! Quiero hacer este pedido:",
};

const PRODUCTOS = [
  {
    id: 1,
    nombre: "Aceite de Oliva Doña Juana 250 ml Clásico-Ajo-Tomate y albahaca",
    categoria: "Aceites",
    descripcion: "",
    imagen: "img/finales/aceite-de-oliva-dona-juana-250ml-clasico-ajo-tomate-y-albahaca.jpg",
  },
  {
    id: 2,
    nombre: "Aceite de Oliva Doña Juana 500 ml Clásico-Ajo-Tomate y albahaca",
    categoria: "Aceites",
    descripcion: "",
    imagen: "img/finales/aceite-de-oliva-dona-juana-500ml-clasico-ajo-tomate-y-albahaca.jpg",
  },
  {
    id: 3,
    nombre: "Aceite de Oliva Mendoliva 900 ml",
    categoria: "Aceites",
    descripcion: "",
    imagen: "img/finales/aceite-de-oliva-mendoliva-900ml.jpg",
  },
  {
    id: 4,
    nombre: "Aceitunas Verdes, Negras y Rellenas con Morrón Casa de La Torre 300 gr",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/aceitunas-verdes-negrasy-rellenas-con-morron-casa-de-la-torre-300gr.jpg",
  },
  {
    id: 5,
    nombre: "Cebollas Caramelizadas 200 gr Doña Juana",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/cebollas-caramelizadas-200gr-casa-de-la-torre.jpg",
  },
  {
    id: 6,
    nombre: "Cerezas al Marrasquino Casa de La Torre",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/cerezas-al-marrasquino-casa-de-la-torre.jpg",
  },
  {
    id: 7,
    nombre: "Higos en Almíbar Casa de La Torre",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/higos-en-almibar-casa-de-la-torre.jpg",
  },
  {
    id: 8,
    nombre: "Hortalizas Asadas Casa de La Torre",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/hortalizas-asadas-casa-de-la-torre.jpg",
  },
  {
    id: 9,
    nombre: "Pasta de Aceitunas varias Casa de La Torre 300 gr",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/pasta-de-aceitunas-varias-casa-de-la-torre-300gr.jpg",
  },
  {
    id: 10,
    nombre: "Peras al Malbec enteras",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/peras-al-malbec-enteras.jpg",
  },
  {
    id: 11,
    nombre: "Tomates Cherry Caramelizados con Malbec 200 gr Doña Juana",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/tomates-cherry-caramelizados-con-malbec-200gr-casa-de-la-torre.jpg",
  },
  {
    id: 12,
    nombre: "Zapallitos en Almíbar Profecía",
    categoria: "Conservas y encurtidos",
    descripcion: "",
    imagen: "img/finales/zapallitos-en-almibar-profecia.jpg",
  },
  {
    id: 13,
    nombre: "Arrope de Uva Mupay 450 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/arrope-de-uva-mupay-450gr.jpg",
  },
  {
    id: 14,
    nombre: "Batata Vainilla 500 gr Profecía",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/batata-vainilla-500gr-profecia.jpg",
  },
  {
    id: 15,
    nombre: "Bocaditos de Membrillo Profecía 30 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/bocaditos-de-membrillo-profecia-30gr.jpg",
  },
  {
    id: 16,
    nombre: "Caja Bocaditos de Membrillo Profecía 28 unidades x 30 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/cja-bocaditos-de-membrillo-profecia-28-uni-x-30gr.jpg",
  },
  {
    id: 17,
    nombre: "Dulce de Alcayota Profecía",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/dulce-de-alcayota-profecia.jpg",
  },
  {
    id: 18,
    nombre: "Dulce de Leche con Estevia Doña Magdalena",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/ddl-con-estevia-magdalena.jpg",
    conEstevia: true,
  },
  {
    id: 19,
    nombre: "Dulce de Leche Milagros del Sol 453 gr (chocolate, clásico y con ron)",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/ddl-m-sol-453gr-chocolate-clasico-ron.jpg",
  },
  {
    id: 20,
    nombre: "Dulce de Leche Milagros del Sol pote 500 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/ddl-m-sol-pote-500gr.jpg",
  },
  {
    id: 21,
    nombre: "Dulce de Leche Milagros del Sol saborizados 280 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/ddl-m-sol-saborizados-c-clasico-280gr.jpg",
  },
  {
    id: 22,
    nombre: "Dulce de Membrillo Profecía 500 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/dulce-de-membrillo-profecia-500gr.jpg",
  },
  {
    id: 23,
    nombre: "Dulce de Membrillo Profecía 900 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/dulce-de-membrillo-profecia-900gr.jpg",
  },
  {
    id: 24,
    nombre: "Dulce de Membrillo Profecía Pan 650 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/dulce-de-membrillo-profecia-pan-650gr.jpg",
  },
  {
    id: 25,
    nombre: "Mermelada de Higo Casa de La Torre 400 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermelada-de-higo-casa-de-la-torre-400gr.jpg",
  },
  {
    id: 26,
    nombre: "Mermelada Frutilla con Malbec La Casita de la Abueli 450 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermelada-frutilla-con-malbec-la-casita-de-la-abueli-450-gr.jpg",
  },
  {
    id: 27,
    nombre: "Mermelada Pera con Torrontés La Casita de la Abueli 450 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermelada-pera-con-torrontes-la-casita-de-la-abueli-450-gr.jpg",
  },
  {
    id: 28,
    nombre: "Mermeladas con Estevia",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermeladas-con-estevia.jpg",
    conEstevia: true,
  },
  {
    id: 29,
    nombre: "Mermeladas Frutos del Bosque y Frutilla Casa de La Torre",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermeladas-frutos-del-bosque-frutilla-casa-de-la-torre.jpg",
  },
  {
    id: 30,
    nombre: "Mermeladas varias La Casita de la Abueli 250 gr",
    categoria: "Dulces y mermeladas",
    descripcion: "",
    imagen: "img/finales/mermeladas-varias-la-casita-de-la-abueli-250gr.jpg",
  },
  {
    id: 31,
    nombre: "Alfajor con Estevia y sin TACC Doña Magdalena 60 gr",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/alfajor-con-estevia-y-sin-tacc-dona-magdalena-60gr.jpg",
    conEstevia: true,
  },
  {
    id: 32,
    nombre: "Alfajor Maicena Churrico",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/alfajor-maicena-churrico.jpg",
  },
  {
    id: 33,
    nombre: "Alfajores Churrico Clasicos Negro- Blanco y con Crocante de Maní 75 gr",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/alfajores-churrico-clasicos-negro-blanco-y-con-crocate-de-mani-75gr.jpg",
  },
  {
    id: 34,
    nombre: "Alfajores de Arroz Negro y Blanco, Dulce de Leche y Pistacho",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/alfajores-de-arroz-negro-blanco-ddl-y-pistacho.jpg",
  },
  {
    id: 35,
    nombre: "Almohaditas Avena Granix Frutilla- Chocolate con limon",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/almohaditas-avena-granix-frutilla-chocolate-con-limon.jpg",
  },
  {
    id: 36,
    nombre: "Caja Alfajores con Estevia y sin TACC Doña Magdalena 60 gr x 12",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/caja-alfajores-con-estevia-y-sin-tacc-dona-magdalena-60gr-x-12.jpg",
    conEstevia: true,
  },
  {
    id: 37,
    nombre: "Conitos Churrico",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/conitos-churrico.jpg",
  },
  {
    id: 38,
    nombre: "Galletas YUKA sin TACC",
    categoria: "Alfajores y galletas",
    descripcion: "",
    imagen: "img/finales/galletas-yuka-sin-tacc.jpg",
  },
  {
    id: 39,
    nombre: "Bombones de Fruta Abuela Mecha bolsas x 4",
    categoria: "Chocolates",
    descripcion: "",
    imagen: "img/finales/bombones-de-fruta-abuela-mecha-bolsas-x-4.jpg",
  },
  {
    id: 40,
    nombre: "Chocolate Colonial con Estevia y Orgánico",
    categoria: "Chocolates",
    descripcion: "",
    imagen: "img/finales/chocolate-colonial-con-stevia-y-organico.jpg",
    conEstevia: true,
  },
  {
    id: 41,
    nombre: "Tableta de Dulce de Leche con Estevia",
    categoria: "Chocolates",
    descripcion: "",
    imagen: "img/finales/tableta-ddl-con-estevia.jpg",
    conEstevia: true,
  },
  {
    id: 42,
    nombre: "Almendras bolsa grande",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/almendras-bolsa-grande.jpg",
  },
  {
    id: 43,
    nombre: "Almendras, cereales, maní y pasas bañadas en chocolate",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/almendras-cereales-mani-pasas-banadas-en-chocolate.jpg",
  },
  {
    id: 44,
    nombre: "Maní Varios: con y sin sal, saborizados y garrapiñadas",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/mani-varios-con-y-sin-sal-saborizados-y-garrapinadas.jpg",
  },
  {
    id: 45,
    nombre: "Mix Tropical bolsa grande",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/mix-tropical-bolsa-grande.jpg",
  },
  {
    id: 46,
    nombre: "Mix-Nuez-Almendras bolsas chicas",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/mix-nuez-almendras-bolsas-chicas.jpg",
  },
  {
    id: 47,
    nombre: "Nuez Mariposa bolsa grande",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/nuez-mariposa-bolsa-grande.jpg",
  },
  {
    id: 48,
    nombre: "Pasas Morenas",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/pasas-morenas.jpg",
  },
  {
    id: 49,
    nombre: "Pasas Rubias",
    categoria: "Frutos secos",
    descripcion: "",
    imagen: "img/finales/pasas-rubias.jpg",
  },
  {
    id: 50,
    nombre: "Barras Bravísima y Proteica",
    categoria: "Barras y snacks",
    descripcion: "",
    imagen: "img/finales/barras-bravisima-y-proteica.jpg",
  },
  {
    id: 51,
    nombre: "Palitos salados",
    categoria: "Barras y snacks",
    descripcion: "",
    imagen: "img/finales/palitos-salados.jpg",
  },
  {
    id: 52,
    nombre: "Tutucas con azúcar y estevia",
    categoria: "Barras y snacks",
    descripcion: "",
    imagen: "img/finales/tutucas-con-azucar-estevia.jpg",
    conEstevia: true,
  },
  {
    id: 53,
    nombre: "Jugos Naturales Concentrados y Limonadas, varios, Casa de La Torre 500 ml",
    categoria: "Bebidas",
    descripcion: "",
    imagen: "img/finales/jugos-natureles-concentados-limonadas-varios-casa-de-la-torre-500ml.jpg",
  },
  {
    id: 54,
    nombre: "Mistela Crotta 75cl",
    categoria: "Bebidas",
    descripcion: "",
    imagen: "img/finales/mistela-crotta-75cl.jpg",
  },
  {
    id: 55,
    nombre: "Miel Trasancos 500 gr",
    categoria: "Miel",
    descripcion: "",
    imagen: "img/finales/miel-trasancos-500gr.jpg",
  },
  {
    id: 56,
    nombre: "Sal Entrefina Saborizada Malbec, Finas Hierbas y Romero 200 gr",
    categoria: "Sales",
    descripcion: "",
    imagen: "img/finales/sal-entrefina-saborizada-malbec-finas-hierbas-romero-200gr.jpg",
  },
  {
    id: 57,
    nombre: "Pañuelos",
    categoria: "Otros",
    descripcion: "",
    imagen: "img/finales/panuelos.jpg",
  },
];
